// DashboardForm.Designer.cs
using System;
using System.Drawing;
using System.Windows.Forms;

namespace QuizierApp
{
    partial class DashboardForm
    {
        private System.ComponentModel.IContainer components = null;

        // Controls
        private Label lblWelcome;     // <<< ADD THIS DECLARATION
        private PictureBox pbLogo;
        private Button btnStartQuiz;
        private Button btnViewScores;
        private Button btnAdminPanel;
        //private Button btnSettings;
        private Button btnLogout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        // IMPORTANT: This method is regenerated by the designer.
        // Do not modify manually unless you know what you are doing!
        // IMPORTANT: This method is regenerated by the designer.
        // Do not modify manually unless you know what you are doing!
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();

            // --- Declare Controls (Designer does this) ---
            this.lblWelcome = new System.Windows.Forms.Label();
            this.pbLogo = new System.Windows.Forms.PictureBox();
            this.btnStartQuiz = new System.Windows.Forms.Button();
            this.btnViewScores = new System.Windows.Forms.Button();
            this.btnAdminPanel = new System.Windows.Forms.Button();
            //this.btnSettings = new System.Windows.Forms.Button();
            this.btnLogout = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.pbLogo)).BeginInit();
            this.SuspendLayout();

            //
            // Form setup
            //
            this.ClientSize = new System.Drawing.Size(1366, 768);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Dashboard";
            this.Name = "DashboardForm";
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(45)))));

            //
            // lblWelcome
            //
            this.lblWelcome.AutoSize = false;
            this.lblWelcome.BackColor = System.Drawing.Color.Transparent;
            this.lblWelcome.Dock = System.Windows.Forms.DockStyle.Top; // Docked to top
            this.lblWelcome.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblWelcome.ForeColor = System.Drawing.Color.White;
            this.lblWelcome.Location = new System.Drawing.Point(0, 0); // Positioned by Dock
            this.lblWelcome.Name = "lblWelcome";
            this.lblWelcome.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.lblWelcome.Size = new System.Drawing.Size(1366, 30); // Width matches form, Height = 30
            this.lblWelcome.TabIndex = 0;
            this.lblWelcome.Text = "Welcome!";
            this.lblWelcome.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;

            // --- Define Constants for Layout ---
            int centerX = this.ClientSize.Width / 2;
            int logoTopMargin = 40; // Space below lblWelcome
            int buttonsTopMargin = 40; // Space below pbLogo
            int btnWidth = 200;
            int btnHeight = 50;
            int buttonSpacing = 20; // Vertical space between buttons

            //
            // pbLogo
            //
            int logoActualY = this.lblWelcome.Height + logoTopMargin; // Y pos below the welcome label
            int logoX = centerX - (this.pbLogo.Width / 2);
            this.pbLogo.Location = new System.Drawing.Point(logoX, logoActualY);
            this.pbLogo.Name = "pbLogo";
            string logoPath = @"C:\Users\ahmed\OneDrive\Pictures\logo\quizierLogo.png";
            try { this.pbLogo.Image = Image.FromFile(logoPath); } catch { /* Add logging */ }
            // Note: Set Size *before* calculating X position if Width isn't already known
            this.pbLogo.Size = new System.Drawing.Size(200, 200);
            logoX = centerX - (this.pbLogo.Width / 2); // Recalculate X after setting size
            this.pbLogo.Location = new System.Drawing.Point(logoX, logoActualY); // Set final location
            this.pbLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbLogo.TabIndex = 1;
            this.pbLogo.TabStop = false;

            // --- Calculate Button Positions ---
            int firstBtnY = this.pbLogo.Bottom + buttonsTopMargin; // Y position for the first button (below logo)
            int btnX = centerX - (btnWidth / 2); // Centered X position for buttons

            //
            // btnStartQuiz
            //
            this.btnStartQuiz.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.btnStartQuiz.FlatAppearance.BorderSize = 0;
            this.btnStartQuiz.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStartQuiz.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.btnStartQuiz.ForeColor = System.Drawing.Color.White;
            this.btnStartQuiz.Location = new System.Drawing.Point(btnX, firstBtnY); // Use calculated X and Y
            this.btnStartQuiz.Name = "btnStartQuiz";
            this.btnStartQuiz.Size = new System.Drawing.Size(btnWidth, btnHeight);
            this.btnStartQuiz.TabIndex = 2;
            this.btnStartQuiz.Text = "Start Quiz";
            this.btnStartQuiz.UseVisualStyleBackColor = false;

            //
            // btnViewScores
            //
            this.btnViewScores.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.btnViewScores.FlatAppearance.BorderSize = 0;
            this.btnViewScores.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnViewScores.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.btnViewScores.ForeColor = System.Drawing.Color.White;
            // Position below previous button using buttonSpacing
            this.btnViewScores.Location = new System.Drawing.Point(btnX, firstBtnY + (btnHeight + buttonSpacing));
            this.btnViewScores.Name = "btnViewScores";
            this.btnViewScores.Size = new System.Drawing.Size(btnWidth, btnHeight);
            this.btnViewScores.TabIndex = 3;
            this.btnViewScores.Text = "View Scores";
            this.btnViewScores.UseVisualStyleBackColor = false;

            //
            // btnAdminPanel
            //
            this.btnAdminPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.btnAdminPanel.FlatAppearance.BorderSize = 0;
            this.btnAdminPanel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdminPanel.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.btnAdminPanel.ForeColor = System.Drawing.Color.White;
            this.btnAdminPanel.Location = new System.Drawing.Point(btnX, firstBtnY + 2 * (btnHeight + buttonSpacing));
            this.btnAdminPanel.Name = "btnAdminPanel";
            this.btnAdminPanel.Size = new System.Drawing.Size(btnWidth, btnHeight);
            this.btnAdminPanel.TabIndex = 4;
            this.btnAdminPanel.Text = "Admin Panel";
            this.btnAdminPanel.UseVisualStyleBackColor = false;

            //
            // btnSettings
            //
            //this.btnSettings.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            //this.btnSettings.FlatAppearance.BorderSize = 0;
            //this.btnSettings.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            //this.btnSettings.Font = new System.Drawing.Font("Segoe UI", 14F);
            //this.btnSettings.ForeColor = System.Drawing.Color.White;
            //this.btnSettings.Location = new System.Drawing.Point(btnX, firstBtnY + 3 * (btnHeight + buttonSpacing));
            //this.btnSettings.Name = "btnSettings";
            //this.btnSettings.Size = new System.Drawing.Size(btnWidth, btnHeight);
            //this.btnSettings.TabIndex = 5;
            //this.btnSettings.Text = "Settings";
            //this.btnSettings.UseVisualStyleBackColor = false;

            //
            // btnLogout
            //
            this.btnLogout.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnLogout.BackColor = System.Drawing.Color.Firebrick;
            this.btnLogout.FlatAppearance.BorderSize = 0;
            this.btnLogout.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLogout.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnLogout.ForeColor = System.Drawing.Color.White;
            this.btnLogout.Location = new System.Drawing.Point(this.ClientSize.Width - 110 - 25, this.ClientSize.Height - 35 - 20);
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.Size = new System.Drawing.Size(110, 35);
            this.btnLogout.TabIndex = 6;
            this.btnLogout.Text = "Logout";
            this.btnLogout.UseVisualStyleBackColor = false;

            //
            // Add Controls to Form
            //
            this.Controls.Add(this.lblWelcome); // Label is added first
            this.Controls.Add(this.pbLogo);
            this.Controls.Add(this.btnStartQuiz);
            this.Controls.Add(this.btnViewScores);
            this.Controls.Add(this.btnAdminPanel);
            //this.Controls.Add(this.btnSettings);
            this.Controls.Add(this.btnLogout);

            ((System.ComponentModel.ISupportInitialize)(this.pbLogo)).EndInit();
            this.ResumeLayout(false);

            // Bring label to front (often redundant with Dock=Top, but safe)
            this.lblWelcome.BringToFront();

        } // End InitializeComponent

    } // End Partial Class
} // End Namespace